version: '3.8'

services:
  db:
    image: postgres:16.0
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    expose:
      - 5432
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend_project.wsgi
    volumes:
      - static_files_prod:/code/staticfiles
      - media_prod:/code/media
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx: 
    build: ./nginx
    volumes:
      - static_files_prod:/code/staticfiles
      - media_prod:/code/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data_prod:
  static_files_prod:
  media_prod:

