services:
  db:
    image: postgres:16.0
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media_dev:/code/media
      - static_files_dev:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  media_dev:
  static_files_dev:
  postgres_data_dev:

