# Generated by Django 5.0.4 on 2024-04-27 11:29

import blog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=720, upload_to='', width_field=1280)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Article Resource', 'verbose_name_plural': 'Article Resources'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.FileField(upload_to='', validators=[blog.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='article',
            name='related_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.image'),
        ),
        migrations.AddField(
            model_name='resource',
            name='related_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.image'),
        ),
    ]
