# Generated by Django 5.0.4 on 2024-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aditional_info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
