# Generated by Django 5.0.4 on 2024-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='url',
            new_name='file',
        ),
    ]
