# Generated by Django 5.0.4 on 2024-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_url_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.CharField(default='Default Resume', max_length=200),
        ),
    ]
