# Generated by Django 5.0.4 on 2024-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_author_article_author_alter_resource_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='resume',
            field=models.CharField(default='Default Resume', max_length=200),
        ),
    ]
